### ISSUE TITLE
Enabling solaire mode in only a few (file) buffer

### ISSUE THREAD

**Issue by lepisma** [hlissner/emacs-solaire-mode#1]
Hello,

I am a happy user of your doom themes (they are great!).
With the recent update, I started setting up solaire mode. Earlier, I enabled `doom-buffer-mode` only for `prog-mode` and it worked well (I liked org and other text modes to be darker). Now with solaire mode, I can't get this behavior and every buffer visiting a file is getting bright background, even without adding any hooks.

I suspect this is because of [this advice](https://github.com/hlissner/emacs-solaire-mode/blob/master/solaire-mode.el#L176)

```
(advice-add #'persp-load-state-from-file :after #'solaire-mode--persp-mode-reload)
```

Any ideas?

*In case this helps*, I am using spacemacs and `doom-molokai` theme.

**Comment by hlissner** [comment]
Ah, in hindsight, that advice _is_ too aggressive. I'll fix that.

Though, just to clarify, you're using persp-mode, correct?

**Comment by lepisma** [comment]
Yes. Also, as a temporary fix, removing that advice works for me.

**Comment by hlissner** [comment]
I've made the persp-mode advice optional. I'll consider this resolved. Thanks for reporting it!
