### ISSUE TITLE
variable-pitch-mode

### ISSUE THREAD

**Issue by jupl** [hlissner/emacs-solaire-mode#10]
When I enable variable-pitch-mode for any buffer, the moment I switch to another buffer that does not have variable-pitch mode while I am using solaire-mode, variable-pitch text is on even though the mode is disabled. For example, I open an org file, turn on variable-pitch-mode, then open/switch to another file and it is variable-pitch even though it is not supposed to be.

**Comment by hlissner** [comment]
Sorry for the late reply! I'm hoping df92c33 has addressed this issue. Please update and let me know if it does.

NOTE: this is the same as #15, but since the discussion there is longer I'll mark this one as the duplicate. Please continue the discussion there.
