### ISSUE TITLE
Fix doom-themes instead of recommending workaround?

### ISSUE THREAD

**Issue by alphapapa** [hlissner/emacs-solaire-mode#13]
Hi,

Finally got around to trying this package.  It's very nice!  :)

I usually use `solarized-light`, but sometimes I use `doom-themes`.  I noticed that in the readme you recommend using `(solaire-mode-swap-bg)` as a workaround.

I looked at some of the code for `doom-themes` and it seems to set the `solaire-mode` faces so that file-backed buffers are darker rather than lighter.  For example, in `doom-themes-common.el`:

```el
(solaire-default-face  :inherit 'default :background bg-alt)
(solaire-hl-line-face  :inherit 'hl-line :background bg)
(solaire-org-hide-face :foreground bg-alt)
```

So it seems that `doom-themes` is doing the opposite of how `solaire-mode` intends the colors to work.  If that's intentional, I guess that's their artistic intent, and the `(solaire-mode-swap-bg)` workaround makes sense.  But could it just be a mistake on their part?  If so, it might make sense to fix it in `doom-themes` so the workaround would be unnecessary.

Thanks for your work on this package.

**Comment by hlissner** [comment]
It was intentional, but not for any artistic reason. I simply didn't want non-solaire-mode users to have the darker background by default. I'd rather solaire-mode users take the extra step instead.
