### ISSUE TITLE
Incompatible  with text-scale-mode

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-solaire-mode#15]
`solaire-mode` will change the default faces of frame. If enable `text-scale-mode` in one buffer, the text size of other buffers will be impacted, but `text-scale-mode` is buffer-local. The issue disappears after disabling `solaire-mode`.  I am using GNU Emacs 26.1 on macOS Mojave. `solaire-mode` is the latest version.

**Comment by seagle0128** [comment]
I think it's similar as #8 since `text-scale-mode` is also trying to remap the `default` face. But I couldn't find a workaround to address it.

**Comment by alphapapa** [comment]
Something seems strange here.  According to everything I can find, `face-remapping-alist` is a buffer-local variable.  But when I set it in one buffer, like in an Org buffer, with:

```el
(face-remap-add-relative 'default '(:inherit variable-pitch))
```
...and then find an elisp file in another buffer, its local value is the same as the Org buffer's local value:

```
face-remapping-alist is a variable defined in ‘C source code’.
Its value is shown below.

  This variable’s buffer-local value is permanent.

Documentation:
...

Value:
((default
   (:inherit variable-pitch)
   default)
 (hl-line solaire-hl-line-face)
 (org-hide solaire-org-hide-face)
 (org-indent solaire-org-hide-face)
 (mode-line solaire-mode-line-face)
 (mode-line-inactive solaire-mode-line-inactive-face))
Local in buffer init.el; global value is nil
```
The doc for `face-remap-add-relative` says:

> Add a face remapping entry of FACE to SPECS in the current buffer.

Am I missing something, or is there a bug in Emacs here?

**Comment by alphapapa** [comment]
Here's another way to look at it:

1.  Load solaire:
```el
(use-package solaire-mode
  :hook
  ((change-major-mode after-revert ediff-prepare-buffer) . turn-on-solaire-mode)
  (minibuffer-setup . solaire-mode-in-minibuffer))
```
2.  Find an Org file.
3.  Run command `variable-pitch-mode`.
4.  Find an elisp file.

The new elisp buffer's `default` face will be remapped to `variable-pitch`.

**Comment by seagle0128** [comment]
Hello @hlissner  @alphapapa,

I checked this issue again today. I suspect this is related. `solaire-mode--face-remap-add-relative` changes the original behaviors of `face-remap-add-relative`, and may make it be not buffer-local.

```
(defun solaire-mode--face-remap-add-relative (orig-fn &rest args)
  "Minimize interference from other themes, functions and/or packages trying to
remap their own faces (like `text-scale-set')."
  (when solaire-mode
    (let ((remap (assq (nth 0 args) face-remapping-alist)))
      (when remap (setf (nth 0 args) (cadr remap)))))
  (apply orig-fn args))
(advice-add #'face-remap-add-relative :around #'solaire-mode--face-remap-add-relative)
```

I remove this advice and seems work fine, but I don't know if there is side effect.

**Comment by seagle0128** [comment]
I found some clues. `solaire-mode-remap-alist` is changed somehow after setting font size, thus cause  invalid `face-remapping-alist`.

e.g.
![image](https://user-images.githubusercontent.com/140797/52626548-600bf000-2eee-11e9-90e8-d2a65e19501b.png)

I don't know why `solaire-mode-remap-alist` was changed, but it should be a constant IMO.

```elisp
(defcustom solaire-mode-remap-alist
  '(((default solaire-default-face)                       . t)
    ((hl-line solaire-hl-line-face)                       . t)
    ((org-hide solaire-org-hide-face)                     . t)
    ((org-indent solaire-org-hide-face)                   . t)
    ((linum solaire-line-number-face)                     . solaire-mode-remap-line-numbers)
    ((line-number solaire-line-number-face)               . solaire-mode-remap-line-numbers)
    ((mode-line solaire-mode-line-face)                   . solaire-mode-remap-modeline)
    ((mode-line-inactive solaire-mode-line-inactive-face) . solaire-mode-remap-modeline)
    ((highlight-indentation-face soalire-hl-line-face)    . (featurep 'highlight-indentation)))
  "An alist of faces to remap when enabling `solaire-mode'."
  :group 'solaire-mode
  :type '(list face))
```

**Comment by hlissner** [comment]
@seagle0128 ec27b5e should hopefully address that behavior. Let me know if that resolves the issue.

**Comment by seagle0128** [comment]
@hlissner Unfortunately the issue still exists. I am thinking if `solaire-mode--face-remap-add-relative` impacts this because `face-remap-add-relative` is called by `text-scale-mode`.

**Comment by awkspace** [comment]
Same issue, different reason (using `face-remap-add-relative` in my personal config rather than another minor mode). The intent was to set a buffer font for `markdown-mode` , but the font bleeds over into any new buffers I create after opening a Markdown file, `markdown-mode` or not.

This makes `solaire-mode` nonfunctional in Markdown buffers (they are always dark). However, `solaire-mode` works just fine in the other "poisoned" buffers despite having the custom font applied to them.

What I find odd about this is that running `face-remap-remove-relative` on a single "poisoned" buffer instantly fixes the issue for all other "poisoned" buffers without impacting the Markdown buffers. Since `face-remapping-alist` is supposed to be buffer-local, I'm not sure why that would happen.

**Comment by hlissner** [comment]
df92c33 should hopefully address this issue. Please try it and let me know if that's the case.

**Comment by seagle0128** [comment]
@hlissner There is no text-scale issue in my env, but it seems `solaire-mode-swap-bg` doesn't work while `find-file` now?

**Comment by hlissner** [comment]
I'm not sure I understand the problem. How is solaire-mode-swap-bg and find-file related?

**Comment by seagle0128** [comment]
@hlissner Sorry for confusion! After this change, the `text-scale` issue doesn't exist, but it fails this case: if open a new file, the backgrounds are not swapped although `solaire-mode-swap-bg` is called. I have to revert the buffer (bind to `F5` in my env) to swap the colors. Please refer to the recording below.

![emacs](https://user-images.githubusercontent.com/140797/53791253-89eb8c00-3f5b-11e9-997b-a13b24127cdc.gif)

**Comment by seagle0128** [comment]
Update: @hlissner I found using `after-change-major-mode-hook` instead of `change-major-mode-hook` works for me.
