### ISSUE TITLE
copy-seq or copy-sequence

### ISSUE THREAD

**Issue by weavejester** [hlissner/emacs-solaire-mode#16]
In commit ec27b5ee73e209ee3222fdb0cf8b3655319273e3 a call to `copy-seq` was introduced. However, that's not a function that Emacs 26.1 seems to recognize, and the Elisp manual only has a [copy-sequence](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sequence-Functions.html) function.

**Comment by hlissner** [comment]
`copy-seq` is an alias for `copy-sequence` defined at the C level in Emacs (iirc, in Emacs 25.x it's an alias for `cl-copy-seq`). I'm certain it's in 26.1 (I use it regularly on 26.1 and 27 on MacOS and Arch). What build of Emacs are you using?

That said, I'll happily change it to copy-sequence, but I am curious. This isn't the only place I've used copy-seq.

**Comment by weavejester** [comment]
I'm using the the latest Homebrew build of [Railwaycat build of Emacs 26.1 for MacOS](https://github.com/railwaycat/homebrew-emacsmacport/). It has `copy-sequence` but not `copy-seq`. I believe the latter is an alias?

**Comment by weavejester** [comment]
> I believe the latter is an alias?

I've just reread your comment and I now realise that was the first thing you said 🤦‍♂️

**Comment by weavejester** [comment]
The released update (20190216.103) works fine on my emacs version now. Thanks for the update!
