### ISSUE TITLE
Add solaire-fringe-face

### ISSUE THREAD

**Issue by axgfn** [hlissner/emacs-solaire-mode#19]
I was looking to add support for solaire-mode to [parchment-theme](https://github.com/ajgrf/parchment), but I don't like that solaire changes the fringe. It would be nice if there were a face like `solaire-fringe-face` to make it configurable.

**Comment by hlissner** [comment]
I've added a `solaire-mode-remap-fringe` option to make it easier to disable this behavior, and a `solaire-fringe-face`, whose :background the newly affected fringe will adopt, so you can customize the exact background it will use.

**Comment by axgfn** [comment]
Thank you for the quick response, I just pushed support for solaire-mode to parchment-theme! It seems to work fine for me, although you may have forgotten to update the README.
