### ISSUE TITLE
Can we fix the weird fringe issue?

### ISSUE THREAD

**Issue by tam5** [hlissner/emacs-solaire-mode#21]
When opening treemacs, it looks like there is a fringe which is highlighted with the same color as the background and it looks buggy.

What i've noticed, is that creating a new split seems to fix this, but the fix does not stick around.

I am wondering if there may be a way to tap into this "fix" behavior, and trigger it to run when appropriate (unless of course there is a more correct and permanent solution).

Here is what I am talking about:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11488762/57310885-99e92e80-70b8-11e9-9ad9-bf9fd89f9b21.gif)

**Comment by tam5** [comment]
well i was able to hack it away by adding this

```elisp
(after! treemacs
  (advice-add '+treemacs--init :after #'balance-windows))
```

dunno if there is a better solution, feel free to close

**Comment by hlissner** [comment]
The screencast is too small to see what exactly you mean, but a combination of https://github.com/hlissner/emacs-solaire-mode/commit/2be8aa01a2f5e9c42a67e20fecd16cb53eac08ec and upgrading to Emacs 27.x should fix this (as it adds the ability to buffer-locally change the fringe face). If you are on 26.x or older I suggest you upgrade (Doom will be dropping 26.x support late next month in any case).

Alternatively, `(setq solaire-mode-remap-fringe nil)` will stop solaire mode from tinkering with the fringe at all.

In any case, I'll consider this resolved.
