### ISSUE TITLE
Centaur Tabs background strangely affected by Solaire

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-solaire-mode#29]
I'm opening this issue by the request of @ema2159, author of [Centaur Tabs](https://github.com/ema2159/centaur-tabs)
Original issue is [here](https://github.com/ema2159/centaur-tabs/issues/47)

Note the bg color:
![Screenshot from 2019-08-13 09-47-56](https://user-images.githubusercontent.com/19470159/62920937-d612e600-bdaf-11e9-8153-9ac80bbf327e.png)

I'm clicking `*Messages*`. Note that bg is lighter now:
![Screenshot from 2019-08-13 09-48-15](https://user-images.githubusercontent.com/19470159/62920942-da3f0380-bdaf-11e9-9b63-d676e2881743.png)

I'm clicking `*Messages*` again. Bg restored to previous state
![Screenshot from 2019-08-13 09-48-03](https://user-images.githubusercontent.com/19470159/62920946-e034e480-bdaf-11e9-9276-20f874d64f4d.png)

This doesn't happen when solaire-mode is disabled. Happens with all DOOM Themes on Emacs 26.2

**Comment by hlissner** [comment]
As of https://github.com/hlissner/emacs-solaire-mode/commit/2be8aa01a2f5e9c42a67e20fecd16cb53eac08ec this should (mostly) no longer be a problem, as solaire-mode is no longer activate in "real" buffers.

That said, if the problem persists, it may be best to tweak the `tab-line*`, `tab-bar*`, and `centaur-tabs*` family of faces, then PR those fixes to doom-themes, if it's still an issue.

**Comment by andreyorst** [comment]
Thanks! I've noticed the change, but it was a bit hard to find where the changelog is without digging the commit history. I'm not using centaur-tabs since Emacs has native tab support, which I've customized by hand, and they did not have this problem.
