### ISSUE TITLE
Enable solaire on hydra buffer

### ISSUE THREAD

**Issue by scast** [hlissner/emacs-solaire-mode#3]
Not really a issue, more of a question.

Is it possible to enable solaire in the buffer that is created when a hydra keybinding is running? 

Thanks.

**Comment by hlissner** [comment]
Hydra doesn't offer any hooks to attach to, but it does use the `lv` library (and its `lv-window` function) to create the hydra window, so it can be advised. Here is what worked for me:

```emacs-lisp
(defun turn-on-solaire-mode-in-hydra ()
  (when (and lv-wnd (window-live-p lv-wnd))
    (with-selected-window lv-wnd
      (solaire-mode +1))))
(advice-add #'lv-window :after #'turn-on-solaire-mode-in-hydra)
```

**Comment by scast** [comment]
Thank you very much.
