### ISSUE TITLE
Add support for hl-fill-column-mode

### ISSUE THREAD

**Issue by bricewge** [hlissner/emacs-solaire-mode#30]
It would be nice if `hl-fill-colum-face` would behave the same as `hl-line`. I've tried `(add-to-list 'solaire-mode-remap-alist '((hl-fill-column-face solaire-hl-line-face) . t))` to no avail.

**Comment by hlissner** [comment]
This was addressed in hlissner/emacs-doom-themes, but 2be8aa0 also introduces a change in how solaire-mode works, which should indirectly address this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
