### ISSUE TITLE
How to ignore company-box child frame buffers

### ISSUE THREAD

**Issue by jhacksworth** [hlissner/emacs-solaire-mode#33]
Solaire-mode appears to be modifying [company-box](https://github.com/sebastiencs/company-box) child frame buffers, but only after company-box is first invoked and the current theme is switched or modified.

Is there a way to have solaire-mode ignore company-box buffers?

In the following example I'm using the doom-nova theme, but this behavior is not specific to that theme.

[1] First time I'm invoking company-box in this Emacs session, with a Clojure buffer and a Clojure REPL buffer. The company-box/company-tooltip theme colors are in effect for company-box buffers:

<img width="1781" alt="Screen Shot 2020-02-13 at 9 10 24 AM" src="https://user-images.githubusercontent.com/286057/74448955-d2891600-4e49-11ea-98dd-22ad66fef6ba.png">

After I call `Mx counsel-load-theme` and reload the theme, it appears that solaire-mode starts modifying the background color in the company-box buffers. This causes confusion with non-file visiting buffers (such as the Clojure REPL), which have the same background color.

[2] a Clojure buffer and a Clojure REPL buffer after reloading the theme. The company-box/company-tooltip theme background color is no longer in effect:

<img width="1781" alt="Screen Shot 2020-02-13 at 9 11 00 AM" src="https://user-images.githubusercontent.com/286057/74448984-df0d6e80-4e49-11ea-8880-d8d0de4e8c39.png">

**Comment by hlissner** [comment]
Do to a major change in how solaire-mode works, 2be8aa0 should resolve this issue and no longer target company-box frame. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
