### ISSUE TITLE
Header-line face not updating

### ISSUE THREAD

**Issue by skalyan91** [hlissner/emacs-solaire-mode#38]
In buffers where solaire-mode is enabled, the header line matches the (brightened) background colour. However, it retains this brighter colour even when I visit a buffer where solaire mode is off (e.g., Org Agenda). Is this behaviour intended? And is there any way to change it so that the header line always matches the background colour (just as the fringes do)?

**Comment by hlissner** [comment]
2be8aa0 should fix this issue.

If it doesn't, this is largely theme dependent. Please include what theme you're using and screenshots of the behavior.

Otherwise, use `custom-set-faces` to customize the `header-line` face, e.g.

```elisp
(custom-set-faces
  `(header-line ((t (:background "#000000")))))
```
