### ISSUE TITLE
mini-modeline support

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-solaire-mode#43]
From https://github.com/hlissner/emacs-doom-themes/issues/605

I'm using [mini-modeline](https://github.com/kiennq/emacs-mini-modeline) package, that displays modeline in the minibuffer.

In the source code of this package it adds this hook to the minibuffer setup process:

``` emacs-lisp
(defun mini-modeline--set-buffer-face ()
  "Set buffer default face for current buffer."
  (setq mini-modeline--face-cookie
        (face-remap-add-relative 'default mini-modeline-face-attr)))
```

Which effectively colors minibuffer in the color of the modeline as shown here:

![image](https://user-images.githubusercontent.com/19470159/120114614-a8677e80-c188-11eb-9996-b72f5ca0e549.png)

However some themes don't set correct color for the fringes, which result in gaps at the sides of the minibuffer. It would be nice if solaire mode could handle this case.

Solaire Mode commit: 56f6d9e
DOOM Themes commit: `0edc4d2`
Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-30

**Comment by hlissner** [comment]
Give this a try (solaire-global-mode must be loaded/enabled before mini-modeline-mode):

```elisp
(defun fix-mini-modeline--set-buffer-face (&rest _)
  (push (face-remap-add-relative 'fringe mini-modeline-face-attr)
        solaire-mode--remaps))
(advice-add #'mini-modeline--set-buffer-face :after #'fix-mini-modeline--set-buffer-face)
```

**Comment by andreyorst** [comment]
Yes, this seems to work!

**Comment by hlissner** [comment]
As of 56db821 I've added mini-modeline support to the package proper. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by andreyorst** [comment]
Seems to work fine without the advice you've mentioned before. Thanks a lot!
