### ISSUE TITLE
auto-save-visited-mode clears echo area after 5 seconds

### ISSUE THREAD

**Issue by meedstrom** [hlissner/emacs-solaire-mode#47]
### What did you expect to happen?

Enabling auto-save-visited-mode should not change how the echo area behaves.

### What actually happened?

With it enabled, echo area is cleared about 5 seconds after any message. That's obviously troublesome when there is important info.

### Describe your attempts to resolve the issue

Since the problem does not exist in `emacs -Q` (my initial bug report is at http://debbugs.gnu.org/cgi/bugreport.cgi?bug=50224), I bisected my init files and tracked it down to the `:ui doom` module.

### Steps to reproduce

1. Enable the :ui doom module
2. Start Emacs
3. `M-x auto-save-visited-mode RET`
4. You should see the message "Auto-save-visited-mode enabled"
5. Wait about 5 seconds
6. It's gone

### System Information

https://pastebin.com/DfhCuPq3

**Comment by hlissner** [comment]
As of 2eae245 this should be fixed. It may take a couple days before I bump the `:ui doom` module and Doom sees this fix, so in the meantime use my `defadvice!` snippet (or [unpin the `solaire-mode` package](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#pinning-packages-to-specific-commits), run `doom sync -u`, then restart Emacs).
