### ISSUE TITLE
Invert colors of buffers

### ISSUE THREAD

**Issue by konrad1977** [hlissner/emacs-solaire-mode#48]
### Describe your request

Right now my "main buffer" is the one that is effected by solaire-default-face. It would be good to be able to configure it the otherway around so I can set the theme of the other buffers instead. 

Maybe its already possible?

I guess its better to ask this before the release of Elden Ring :) 

### Briefly explain its use-case

Invert the buffers that should be effected by solaire-mode

**Comment by hlissner** [comment]
See https://github.com/hlissner/emacs-solaire-mode/issues/52#issuecomment-2041511576 for examples on how to do this.
