### ISSUE TITLE
Diff changes

### ISSUE THREAD

**Issue by idoo** [hlissner/emacs-solaire-mode#5]
Hello, thank you for that awesome package 👍 

I'm not sure is it related to that package — how that diff changes tool moved to left side before line numbers?

http://take.ms/rwuH2

May be you could you show your emacs config

**Comment by hlissner** [comment]
Sorry for the late response, you can do this with:

```emacs-lisp
;; places the git gutter outside the margins.
(setq-default fringes-outside-margins t)
```

**Comment by hlissner** [comment]
I'll assume this has answered your question. Feel free to reopen otherwise.
