### ISSUE TITLE
Incorrect background color in the Treemacs buffer

### ISSUE THREAD

**Issue by jumper047** [hlissner/emacs-solaire-mode#51]
### What would you like to know?

Seems like one of the last commits to the Treemacs broke solaire-mode. I opened issue in it's repo - https://github.com/Alexander-Miller/treemacs/issues/1024 . Just in case someone went here with same issue there is a workaround:

```
    (push '(treemacs-window-background-face . solaire-default-face) solaire-mode-remap-alist)
    (push '(treemacs-hl-line-face . solaire-hl-line-face) solaire-mode-remap-alist)
```

**Comment by Alexander-Miller** [comment]
A recent commit in treemacs introduced its own face remapping that can be used outside of solaire mode, like so:

```Elisp
  (face-remap-add-relative 'default 'treemacs-window-background-face)
  (face-remap-add-relative 'fringe  'treemacs-window-background-face)
  (face-remap-add-relative 'hl-line 'treemacs-hl-line-face)
```

Based on the code snippet by @jumper047 solaire already has facilities to work around that, so I think it makes sense that the incompatibility should be resolved from within solaire-mode.

**Comment by hlissner** [comment]
Sorry for taking so long to get to this. I've added these faces to `solaire-mode-remap-alist` in 33c2f1f. Thanks for bringing it to my attention!
