### ISSUE TITLE
How can i make the minibuffer to match its buffer's color

### ISSUE THREAD

**Issue by oxcl** [hlissner/emacs-solaire-mode#52]
### What would you like to know?

how can i make the minibuffer to be the same color of its buffer?
currently even for real buffers the solaire mode is activated for its minibuffer. is this the default behavior? how can this be changed?

**Comment by hlissner** [comment]
This question is a bit vague. The minibuffer (with solaire-mode on) already matches the background of non-real buffers:

![image](https://github.com/hlissner/emacs-solaire-mode/assets/510883/87de3741-ce1e-452e-b25e-c2081ed05d14)

(left window = non-real buffer, right window = real (file-visiting) buffer))

You can swap this by adding your theme to `solaire-mode-themes-to-face-swap`. E.g.

```elisp
(with-eval-after-load 'solaire-mode
  (add-to-list 'solaire-mode-themes-to-face-swap 'doom-tomorrow-night))
```

![image](https://github.com/hlissner/emacs-solaire-mode/assets/510883/06e1cbd6-955e-4fd2-a6fb-9300a3cfa675)

OR you can swap what buffers solaire-mode considers "real" by changing the `solaire-mode-real-buffer-fn` setting. E.g.

```elisp
(with-eval-after-load 'solaire-mode
  (setq solaire-mode-real-buffer-fn (lambda () (not (solaire-mode-real-buffer-p)))))
```

![image](https://github.com/hlissner/emacs-solaire-mode/assets/510883/39df5943-62c2-497d-9eb8-a754a9838f5e)

That said, solaire-mode support also depends on what colors the loaded theme uses for the `default` and `solaire-default-face` faces, so changing your theme is a fourth alternative. The screenshots above use doom-tomorrow-night (from [doom-themes](https://github.com/doomemacs/themes/).

-----

Hope that helps!

**Comment by oxcl** [comment]
thanks. your are awesom @hlissner
