### ISSUE TITLE
Wierd glitches with solaire

### ISSUE THREAD

**Issue by ghost** [hlissner/emacs-solaire-mode#6]
Hey, any idea why my sides look like this?

![screenshot from 2017-12-05 08-46-22](https://user-images.githubusercontent.com/1865041/33595680-454889a0-d999-11e7-8e29-63b8a7dcc781.png)

My config:
```
(use-package 
  doom-themes 
  :init (load-theme 'doom-one t) 
  :config (doom-themes-neotree-config) 
  (doom-themes-org-config))

(use-package solaire-mode
  :init
  (add-hook 'after-change-major-mode-hook #'turn-on-solaire-mode)
  (add-hook 'after-revert-hook #'turn-on-solaire-mode)
  (add-hook 'minibuffer-setup-hook #'solaire-mode-in-minibuffer)
  (add-hook 'ediff-prepare-buffer-hook #'solaire-mode)
  (solaire-mode-swap-bg))
```

**Comment by hlissner** [comment]
Unfortunately, this is unavoidable. Those are Emacs' fringes, which can't be given a buffer-local face, and solaire-mode doesn't consider term buffers to be "real", therefore won't highlight them. In un-highlighted buffers the fringes simply won't match the buffer background.

If this really bugs you, you can get solaire-mode to consider terminal buffers "real", thus highlighting them. You can do this by either:

+ Activating solaire-mode explicitly in term-mode: `(add-hook 'term-mode-hook #'solaire-mode)`
+ Or setting `solaire-mode-real-buffer-fn` to a custom function that will return `t` for buffers you want solaire-mode to consider "real", e.g.

   ```emacs-lisp
   (defun is-buffer-real-p (buffer)
     (or buffer-file-name
        (memq major-mode '(term-mode eshell-mode other-mode)))
   (setq solaire-mode-real-buffer-fn #'is-buffer-real-p)
   ```

Also, you can get rid of the fringes in the minibuffer with:

```emacs-lisp
(defun no-fringes-in-minibuffer ()
  "Disable fringes in the minibuffer window."
  (set-window-fringes (minibuffer-window) 0 0 nil))
(add-hook 'minibuffer-setup-hook #'no-fringes-in-minibuffer)
```

Hope that helps!

**Comment by ghost** [comment]
Thanks for answer! After testing both functions:

`solaire-mode-real-buffer-fn` gives me this effect in `term`:
![screenshot from 2017-12-06 21-02-39](https://user-images.githubusercontent.com/1865041/33682872-32ed8108-dac9-11e7-8c4b-a92a52968cd7.png)

Minibuffer function removes fringes from minibuffer only till I switch to term buffer, then they are back till I restart Emacs.

**Comment by hlissner** [comment]
Ah, sorry, your reply slipped under my radar. Could you run this and let me know if it fixes your issue?

```elisp
(set-face-background 'term nil)
```

This is likely to be an issue with [doom-themes](https://github.com/hlissner/emacs-doom-themes), not solaire-mode.

**Comment by hlissner** [comment]
I'll assume that this has been resolved. I've removed the `:background` attribute from the `term` face in [doom-themes](https://github.com/hlissner/emacs-doom-themes), which should resolve your issue. Please open an issue there if that isn't the case.

**Comment by jessiehildebrandt** [comment]
Necroing this issue because I just ran into this problem myself and found a fix:

term-mode behaves strangely with solaire-mode in some configurations because it appears to manually set the background of its faces to inherit from 'default, ignoring face-remapping-alist.

I was able to fix this by setting the background of the 'term face with a hook in my config:

    (use-package solaire-mode
      ;; ...config details go here...
      :hook 
      (term-mode . (lambda () (set-face-background 'term (face-background 'solaire-default-face)))))

Not the prettiest solution, but it's a functioning workaround for anyone else that might have this issue!
