### ISSUE TITLE
Setting solaire colour

### ISSUE THREAD

**Issue by benwtks** [hlissner/emacs-solaire-mode#9]
How do I add config to my init.el to change the colour of neotree to be darker than the editor (using doom-tomorrow-night), without removing the bg swap which makes it darker but then uses the wrong background colour in the editor

**Comment by hlissner** [comment]
So you are using `solaire-mode-swap-bg`, but you want the background of temporary/popup buffers (like neotree) to be darker?

You'll have to change the background color of `solaire-default-face`:

```elisp
(set-face-background 'solaire-default-face "#000000") ; for example
```

The two colors being used for doom-tomorrow-night are `#1d1f21` and `#232527`. So maybe you want it to be darker than the former? Perhaps `"#141517"`?

**Comment by hlissner** [comment]
I'll assume this issue is resolved. Let me know if that isn't the case and I will reopen it.
